FROM php:5.6-apache

# Install dependencies required for building PHP extensions
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libbz2-dev \
    libxml2-dev \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libmcrypt-dev \
    libtidy-dev

# Install PHP extensions
RUN docker-php-ext-install \
    pdo \
    pdo_pgsql \
    pgsql \
    bcmath \
    bz2 \
    zip \
    gd \
    mysqli \
    xml \
    tidy \
    mcrypt
